name: 'Build Release'
description: 'Build a release'
outputs:
  releaseId:
    description: 'ID of release built'
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'dist/index.js'