name: 'Build Release'
description: 'Build a release'
inputs:
  token:
    description: 'The GITHUB_TOKEN secret'
outputs:
  releaseId:
    description: 'ID of release built'
runs:
  using: 'node12'
  main: 'dist/index.js'